### ISSUE TITLE
Foundry v10 Build 291, 0.7.2 Simply Worldbuilding not working with 29.6.5

### ISSUE THREAD

**Issue by TheFifthRider** [mclemente/healthEstimate#130]
Running healthEstimate 29.6.5 in a 0.7.2 Simply Worldbuilding game on Foundry v10 Build 291 and noted that healthEstimate was not working.

In the console on startup, I get the following stack trace:
```
HealthMonitor.js:28 Health Estimate | Error on function getCharacters(). Token Name: "Red Ringed Rose". Type: "character". ReferenceError: healthEstimate is not defined
    at eval (eval at fraction (worldbuilding.js:6:9), <anonymous>:3:1)
    at fraction (worldbuilding.js:6:35)
    at HealthEstimate.getFraction (logic.js:196:19)
    at getCharacters (HealthMonitor.js:23:41)
    at Object.fn (healthEstimate.js:34:2)
    at #call (foundry.js:724:20)
    at Hooks.call (foundry.js:706:38)
    at Canvas.draw (foundry.js:23693:13)
    at async Scene.view (foundry.js:20901:7)
    at async Game.initializeCanvas (foundry.js:8095:20)
    at async Game.setupGame (foundry.js:7935:5)
    at async Game._initializeGameView (foundry.js:8999:5)
    at async Game.initialize (foundry.js:7825:5)
```

And then whenever I hover over a token, I'm spammed with:
```
foundry.js:747 TypeError: Error thrown in hooked function '' for hook 'refreshToken'. Cannot destructure property 'desc' of 'this.getEstimation(...)' as it is undefined.
[Detected 1 package: healthEstimate]
    at HealthEstimate._handleOverlay (logic.js:76:12)
    at Object.fn (logic.js:29:9)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at SimpleToken.refresh (foundry.js:25225:11)
    at SimpleToken._onHoverIn (foundry.js:25505:10)
    at SimpleToken._onHoverIn (foundry.js:47345:18)
    at MouseInteractionManager.callback (foundry.js:27813:45)
    at MouseInteractionManager._handleMouseOver (foundry.js:27930:17)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerMove (interaction.min.mjs:8:17255)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerMove (interaction.min.mjs:8:16687)```

**Comment by mclemente** [comment]
I'm not sure about the first error, somehow your map is loading before the game is actually setup.
Is that the only error when you hover over a token? The should have another that goes like "Error on getEstimation(). Token Name:..."
What is your Estimation Rule? It's the last setting under the Health Estimate section.

**Comment by TheFifthRider** [comment]
Good call! I did also get the other stack trace, I just didn't see it when I posted the issue.

```
logic.js:186 Health Estimate | Error on getEstimation(). Token Name: "Red Ringed Rose". Type: "character". ReferenceError: healthEstimate is not defined
    at eval (eval at fraction (worldbuilding.js:6:9), <anonymous>:3:1)
    at fraction (worldbuilding.js:6:35)
    at HealthEstimate.getFraction (logic.js:196:19)
    at HealthEstimate.getEstimation (logic.js:155:26)
    at HealthEstimate._handleOverlay (logic.js:76:41)
    at Object.fn (logic.js:32:9)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at SimpleToken._onHoverIn (foundry.js:25515:11)
    at SimpleToken._onHoverIn (foundry.js:47345:18)
    at MouseInteractionManager.callback (foundry.js:27813:45)
    at MouseInteractionManager._handleMouseOver (foundry.js:27930:17)
    at a.emit (index.js:181:35)
    at r.dispatchEvent (interaction.min.mjs:8:12235)
    at r.processPointerMove (interaction.min.mjs:8:17255)
    at t.recursiveFindHit (interaction.min.mjs:8:4098)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.recursiveFindHit (interaction.min.mjs:8:3882)
    at t.findHit (interaction.min.mjs:8:4157)
    at r.processInteractive (interaction.min.mjs:8:12841)
    at r.onPointerMove (interaction.min.mjs:8:16687)
```

The estimation rule I'm using is `healthEstimate.worldbuilding.simpleRule.default` -- that's what was there when I installed the plugin and I haven't dug in a ton to know if I should change it to anything else 🙂

**Comment by mclemente** [comment]
>healthEstimate.worldbuilding.simpleRule.default

Oh, that should've been changed when the module updated. Change it to `const hp = token.actor.system.health; return hp.value / hp.max`, that's the "new default" for a while now. It should work again once you do, assuming you haven't changed it when tinkering with the system.

**Comment by TheFifthRider** [comment]
Worked like a charm! Thanks!
