### ISSUE TITLE
Error on Initialization 

### ISSUE THREAD

**Issue by LachlanMac** [mclemente/healthEstimate#162]
I am developing my own system and wanted to test a few modules.  I have used Health Estimate in 5e successfully, but for whatever reason, it fails to initialize on start up with my system.  

I've attached a screenshot of the error message:

![image](https://user-images.githubusercontent.com/23264467/235095839-8091a73c-74c6-47e9-bbb2-a1377d67dbf5.png)

foundry.js:747 Error: Error thrown in hooked function '' for hook 'setup'. This is not a registered game setting
    at ClientSettings.get (foundry.js:2799:42)
    at sGet (utils.js:85:23)
    at get breakCondition [as breakCondition] (EstimationProvider.js:166:18)
    at HealthEstimate.setup (logic.js:15:31)
    at Object.fn (healthEstimate.js:12:22)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.setupGame (foundry.js:7913:11)
    at Game._initializeGameView (foundry.js:8999:16)
    at Game._initializeView (foundry.js:8975:21)
onError @ foundry.js:747

Reproducing is quite simple, I just refresh and the error shows up.

I am currently in early development of the AVD12 System.  I'm not doing anything special in my foundry Init, but it seems like this error happens before my system init is even finished.

**Comment by LachlanMac** [comment]
This issue was resolved by the fix from sunday.
