### ISSUE TITLE
Player Chars show not more any Text

### ISSUE THREAD

**Issue by R0TEAM** [mclemente/healthEstimate#241]
Have found the last working version is 31.8.1.
All versions above dont show an healt estimate text for player chars anymore .. NPCs work fine.
Get this error in foundry :
healthEstimate.js:3723 Health Estimate | Error on getEstimation(). Token Name: "Varis". Type: "character". Error: Token's fraction is not valid, it probably doesn't have a numerical HP or Max HP value.
    at HealthEstimate.getFraction (healthEstimate.js:3739:10)
    at HealthEstimate.getEstimation (healthEstimate.js:3710:33)
    at HealthEstimate._handleOverlay (healthEstimate.js:3609:42)
    at Object.refreshToken [as fn] (healthEstimate.js:509:23)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at CONFIG.Token.objectClass.applyRenderFlags (foundry.js:28456:11)
    at #applyRenderFlags (foundry.js:27811:44)
    at nn.emit (index.js:89:1)
    at Dt.update (index.js:89:1)
    at Dt._tick (index.js:89:1)

**Comment by mclemente** [comment]
What system are you on? And which system version?

**Comment by R0TEAM** [comment]
Foundry 11.315
D&D5 2.4.1

The new D&D5 v3.x is to buggy/problematic with my mod collection ... the same goes more or less with Foundry v12.x

**Comment by mclemente** [comment]
Then it isn't a bug, sorry. The module stopped supporting dnd5e 2.4.1 on the 31.8.2 release.
