### ISSUE TITLE
Health estimate breaking on v10 Stable Build 284

### ISSUE THREAD

**Issue by Ultixan** [mclemente/healthEstimate#93]
After opening up the token configuration screen, health estimate stops functioning.
Game is hosted on Forge if that affects anything.

Browser in use: Google Chrome Version 105.0.5195.102 (Official Build) (64-bit)
Module version: 29.1

I have disabled all modules other than the forge one I cant disable and breakage still occurs.

Steps to reproduce:
1. Hover over token - Health estimate works
2. Open token configuration, either from character sheet or double right clicking token as GM
3. Hover over token - Health estimate broken

The breakage is on a per token basis.
If the steps above are not done again on a different token, it will keep working on those tokens.

When hovering after it breaks, the following appears in dev tools:
```
foundry.js:691 Foundry VTT | Error thrown in hooked function '' for hook 'refreshToken'
#call @ foundry.js:691
callAll @ foundry.js:645
refresh @ foundry.js:24895
_onHoverIn @ foundry.js:25172
_onHoverIn @ foundry.js:46516
callback @ foundry.js:26244
_handleMouseOver @ foundry.js:26361
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerMove @ interaction.min.mjs:8
foundry.js:711 TypeError: Error thrown in hooked function '' for hook 'refreshToken'. Cannot read properties of null (reading 'off')
    at r.destroy (sprite.min.mjs:8:4223)
    at r.destroy (text.min.mjs:8:17807)
    at HealthEstimate._handleOverlay (logic.js:53:51)
    at Object.fn (logic.js:23:9)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at Token5e.refresh (foundry.js:24895:11)
    at Token5e._onHoverIn (foundry.js:25172:10)
    at Token5e._onHoverIn (foundry.js:46516:18)
    at MouseInteractionManager.callback (foundry.js:26244:45)
onError @ foundry.js:711
#call @ foundry.js:692
callAll @ foundry.js:645
refresh @ foundry.js:24895
_onHoverIn @ foundry.js:25172
_onHoverIn @ foundry.js:46516
callback @ foundry.js:26244
_handleMouseOver @ foundry.js:26361
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerMove @ interaction.min.mjs:8
foundry.js:691 Foundry VTT | Error thrown in hooked function '' for hook 'hoverToken'
#call @ foundry.js:691
callAll @ foundry.js:645
_onHoverIn @ foundry.js:25182
_onHoverIn @ foundry.js:46516
callback @ foundry.js:26244
_handleMouseOver @ foundry.js:26361
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerMove @ interaction.min.mjs:8
foundry.js:711 TypeError: Error thrown in hooked function '' for hook 'hoverToken'. Cannot read properties of null (reading 'off')
    at r.destroy (sprite.min.mjs:8:4223)
    at r.destroy (text.min.mjs:8:17807)
    at HealthEstimate._handleOverlay (logic.js:53:51)
    at Object.fn (logic.js:26:9)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at Token5e._onHoverIn (foundry.js:25182:11)
    at Token5e._onHoverIn (foundry.js:46516:18)
    at MouseInteractionManager.callback (foundry.js:26244:45)
    at MouseInteractionManager._handleMouseOver (foundry.js:26361:17)
onError @ foundry.js:711
#call @ foundry.js:692
callAll @ foundry.js:645
_onHoverIn @ foundry.js:25182
_onHoverIn @ foundry.js:46516
callback @ foundry.js:26244
_handleMouseOver @ foundry.js:26361
a.emit @ index.js:181
r.dispatchEvent @ interaction.min.mjs:8
r.processInteractive @ interaction.min.mjs:8
r.onPointerMove @ interaction.min.mjs:8
```

I also confirmed that disabling the health estimate module causes this error to not appear in dev tools when repeating the steps listed.

**Comment by mclemente** [comment]
Thanks for the report, I noticed an error showing up on console earlier but missed how to reproduce it.
This is actually Core bug (or, at best a dnd5e bug) because closing the settings is nullifying `_texture` from the Token for some reason. I've opened an issue for that https://github.com/foundryvtt/foundryvtt/issues/8079
The good news is that checking for the estimate's `_texture` before calling `destroy` won't break anything, so at least the module won't break because of that.
